name: Deploy Next.js

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nextjs-app .

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -i "$SSH_PRIVATE_KEY" $SERVER_USER@$SERVER_IP << 'EOF'
          docker stop nextjs-container || true
          docker rm nextjs-container || true
          docker run -d -p 3000:3000 --name nextjs-container nextjs-app
          EOF
